syntax on

set number
set background=dark
set expandtab
set autoindent
set smartindent
set shiftwidth=2
set tabstop=2

source $VIMRUNTIME/macros/matchit.vim
"https://stackoverflow.com/questions/7281459/matchit-not-working
filetype plugin on
filetype indent on
