syntax on

set number
set background=dark
set expandtab
set autoindent
set smartindent
set shiftwidth=2
set tabstop=2
set backspace=indent,eol,start
"set clipboard=unnamed,autoselect
"https://yoru9zine.hatenablog.com/entry/2016/12/26/225247
"http://note.kurodigi.com/archlinux-vimclipboard/
"set clipboard=unnamedplus


" Too long line may make vim slower, because of work of syntax highlighting.
" Lower limit of column number to be highlighted can make vim faster.
set synmaxcol=1000

source $VIMRUNTIME/macros/matchit.vim
"https://stackoverflow.com/questions/7281459/matchit-not-working
filetype plugin on
filetype indent on
