#!/usr/bin/env ruby
# coding: utf-8

require 'yaml'

require_relative 'installer'
require_relative 'util'


if (dir = ARGV.first.to_s).empty?

	puts "specify dir"
	exit(1) 

end

Dir::chdir(dir)

YAML.load_file("loc.yaml").map{|type, loc|

	if type == :sym then

		loc.map{ |source_name, target_name|
			install_sym(
				#source_name:  source_name,
				#target_name:  target_name,
				#dest:         to_path(target_name),
				loc:		loc,
				bk_dir: "backups",
				bk_lst: "backups.yaml",
				cur:    Dir::pwd
			) 
		}
	
	else

		raise NotImplementedError.new("type #{type}")

	end

}
