#!/usr/bin/env fish

git config --global credential.helper libsecret

mkdir $HOME/bin

cd custom
mkdir libsec
cd libsec

if not [ -e "git-credential-libsecret.c" ]; and not [ -e Makefile ]
  wget "https://raw.githubusercontent.com/git/git/2cc2e70264e0fcba04f9ef791d144bbc8b501206/contrib/credential/libsecret/Makefile"
  wget "https://raw.githubusercontent.com/git/git/2cc2e70264e0fcba04f9ef791d144bbc8b501206/contrib/credential/libsecret/git-credential-libsecret.c"
end

make
