#!/usr/bin/bash
# https://wiki.archlinux.jp/index.php/Matlab#.E3.82.A2.E3.83.89.E3.82.AA.E3.83.B3.E3.83.9E.E3.83.8D.E3.83.BC.E3.82.B8.E3.83.A3.E3.81.8C.E5.8B.95.E4.BD.9C.E3.81.97.E3.81.AA.E3.81.84

MROOT=$1
TAIL=$2
TAIL2=$3

if [[ -z "${MROOT}" ]]; then
  echo '$MROOT missing'
  exit
fi

if [[ -z "${TAIL}" ]]; then
  echo '$TAIL missing'
  exit
fi

read -p "MROOT=$MROOT, TAIL=$TAIL, TAIL2=$TAIL2  >>"


cd $MROOT/cefclient/sys/os/glnxa64
mkdir backup

libs=(libgio-2.0.so libglib-2.0.so libgmodule-2.0.so libgobject-2.0.so libgthread-2.0.so)
for lib in ${libs[@]}
do
  file=$lib.$TAIL
  echo "mv $file to backup/"
  mv $file backup/

  system=$lib.$TAIL2
  echo "cp /usr/lib/$system $file"
  cp /usr/lib/$system $file
done
