font_family      Fira Code
bold_font        Fira Code Bold
font_size 9.5
tab_bar_style slant
background_opacity 0.5
dynamic_background_opacity yes
color0 #000000
color8 #767676
color3 #f67400
color11 #fdbc4b
color4  #1DAFF3
color12 #3daee9
