[ids]

*

[main]

# Maps capslock to escape when pressed and control when held.
# capslock = overload(control, esc)
#
# # Remaps the escape key to capslock
# esc = capslock

leftalt = overload(altl1, leftalt)

[altl1:A]

\ = ^
