#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
printenv | sed 's/^/export /' > $SCRIPT_DIR/systemenv.sh

SHELL=/opt/gentoo_prefix/x86_64/bin/fish
/opt/gentoo_prefix/x86_64/usr/bin/env -i \
  HOME=$HOME TERM='xterm-256color' USER=$USER SHELL=$SHELL DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY TZ=Asia/Tokyo \
  XDG_DATA_DIRS=$XDG_DATA_DIRS DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR \
  SSH_CLIENT="$SSH_CLIENT" \
  $SHELL -l
