#!/bin/bash

grep gnome ~/.gitconfig

if [ "$?" != "0" ]
then

cat <<-"CAT" >> $HOME/.gitconfig
[credential]
  helper = gnomekeyring
CAT

fi

git clone https://github.com/shugo/git-credential-gnomekeyring.git gcg/
cd gcg/
make
mkdir $HOME/bin
cp git-credential-gnomekeyring $HOME/bin
