#!/bin/bash

git config --global credential.helper $HOME/bin/git-credential-gnome-keyring

git clone https://github.com/shugo/git-credential-gnomekeyring.git gcg/
cd gcg/
make

mkdir $HOME/bin
cp git-credential-gnomekeyring $HOME/bin/git-credential-gnome-keyring
